import React from 'react'

export default function Inversiones() {
    return (
        <section id="inversiones" className='padded'>
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem saepe, maxime eligendi aut architecto praesentium vero vitae pariatur excepturi, quisquam cum ut distinctio dicta perferendis repudiandae ipsum, doloribus alias eaque. Quos aspernatur porro, tempora odit accusamus ipsa quae fugiat inventore iste. Cupiditate, sit veritatis maxime possimus est minima consequatur voluptate a. Laboriosam, sit voluptates harum rem nesciunt magnam sunt maiores sequi eveniet totam nobis cupiditate sint ab sed recusandae corporis est! Error molestias a magnam ad! Cum illum sapiente quia.</p>
                <p>Suscipit obcaecati non repellendus ipsum, quaerat iusto laudantium sapiente eum mollitia saepe eligendi deserunt! Incidunt nulla odio perspiciatis tempora error ipsam cumque cupiditate ab minus reiciendis quibusdam soluta quidem voluptatem dolores facilis, eligendi expedita fugiat debitis quasi molestias labore quae. Sapiente dicta ex, distinctio voluptates quia, sit ratione beatae deserunt, itaque culpa expedita. Alias culpa mollitia recusandae illo asperiores ullam dolores dolorem non, nam obcaecati ducimus dolor laudantium quo consequatur exercitationem nostrum iusto fuga voluptate ipsam enim voluptatum! Saepe, eveniet?</p>
                <p>Cum possimus recusandae culpa. Minus ad non corrupti. Tempore delectus quidem, consequatur, ipsam dolorum iure voluptate incidunt labore libero odit neque ipsum distinctio! Fugit repellendus, animi earum dolore repellat quos ipsa eaque, reiciendis praesentium, dolorem consectetur facere autem aut odio! Commodi recusandae illo natus corporis maiores culpa cum numquam aspernatur. Vel eaque delectus ipsa voluptatum excepturi unde adipisci reiciendis rem ratione doloribus assumenda, culpa officia at placeat nobis reprehenderit asperiores magni quam laborum dolores amet natus itaque! Amet, quo error.</p>
                <p>Culpa consequatur, similique error maxime nesciunt ex dolore ullam ipsum nam doloribus voluptate, necessitatibus id! Officia voluptate iste magnam excepturi accusantium tenetur numquam molestias nisi? Officia, corrupti quis. Eligendi aperiam ea dolores sapiente expedita quos laboriosam animi saepe ratione perferendis praesentium et ab vel rem repellendus cumque officiis adipisci, deserunt commodi. Et sunt non ut nam, corporis veritatis, minima quisquam assumenda, neque ab magnam eaque quis modi velit voluptatum! Non nobis nemo quae fuga debitis enim, a voluptates voluptatem. Provident?</p>
                <p>Placeat, eos, cumque temporibus provident eaque harum saepe rem facere maxime possimus commodi consequuntur sequi hic numquam quibusdam est! Repellendus in voluptas amet autem sapiente provident, quae vel voluptates modi blanditiis animi numquam assumenda eos, incidunt nulla iure libero beatae accusantium reprehenderit molestias maiores sint at consectetur? Nemo odio iure provident adipisci cumque eligendi unde, ad aut incidunt et a quod, debitis exercitationem. Architecto, itaque quo alias iste aliquam obcaecati! Rerum officiis expedita facilis et incidunt voluptate nesciunt, quia consectetur.</p>
                <p>Autem distinctio recusandae, voluptas incidunt voluptatem quasi reiciendis temporibus corrupti cupiditate asperiores veritatis vero fugiat veniam libero quam omnis consequatur, cumque consequuntur blanditiis voluptatibus! Quis libero dolorum laboriosam fugit, quo totam repudiandae ab enim nisi dolore officiis eius animi odio dignissimos fugiat dicta eos minima? Velit doloremque, quaerat ex totam quibusdam consequuntur aut suscipit. Eaque perferendis deleniti consequatur, quaerat dolore illum dolores sunt esse. Repellendus fugit, laudantium illum libero dignissimos est ex veritatis, necessitatibus earum quos, minus eum? Excepturi, vitae.</p>
            </div>
        </section>
    )
}
